### ISSUE TITLE
Client doesn't pick up IP address change in GELF server domain name

### ISSUE THREAD

**Issue by claudemamo** [Graylog2/gelfclient#25] opened 2016-10-27 15:47 UTC
The IP address for the GELF server's domain name was changed but the client didn't pick up the new IP address when using the UDP transport. Instead, it keeps trying to send logs to the old unreachable IP address. I believe the problem is coming from the following line of code: https://github.com/Graylog2/gelfclient/blob/cdb0241e085a9a15fdfb6dce887616a262a95be4/src/main/java/org/graylog2/gelfclient/transport/GelfUdpTransport.java#L62.

[InetSocketAddress only performs resolution at construction time](https://www.tellapart.com/inetsocketaddress-considered-harmful/), and since createBootstrap(...) is just called during initialisation, IP address changes aren't picked up. The current solution is to restart the application but of course this isn't ideal. GelfMessageUdpEncoder's constructor should be changed to take in the hostname and port instead of InetSocketAddress so that they can be used to create an InetSocketAddress object in the encode(...) method.

**Comment by joschi** [comment] 2016-10-27 15:51
Duplicate of #5.

**Closed by joschi** 2016-10-27 15:51 UTC
